### PR TITLE
Handling special characters for table name 

### LINKED ISSUE #38: Special characters in table name cause exception
```
2023-01-14 00:17:35,842 ERROR [clickhouse-sink.cdc.structured-trait-updates.v0|task-0] Got exception when running DESCRIBE TABLE default.pocus.cdc.structured-trait-updates.v0 (com.clickhouse.kafka.connect.sink.db.helper.ClickHouseHelperClient) [task-thread-clickhouse-sink.cdc.structured-trait-updates.v0-0]
com.clickhouse.client.ClickHouseException: Code: 62. DB::Exception: Syntax error: failed at position 44 ('-'): -trait-updates.v0. Expected one of: token, Dot. (SYNTAX_ERROR) (version 22.9.3.18 (official build))
, server ClickHouseNode [uri=http://clickhouse:8123/default]
	at com.clickhouse.client.ClickHouseException.of(ClickHouseException.java:148)
	at com.clickhouse.client.AbstractClient.lambda$execute$0(AbstractClient.java:291)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: Code: 62. DB::Exception: Syntax error: failed at position 44 ('-'): -trait-updates.v0. Expected one of: token, Dot. (SYNTAX_ERROR) (version 22.9.3.18 (official build))

	at com.clickhouse.client.http.HttpUrlConnectionImpl.checkResponse(HttpUrlConnectionImpl.java:187)
	at com.clickhouse.client.http.HttpUrlConnectionImpl.post(HttpUrlConnectionImpl.java:278)
	at com.clickhouse.client.http.ClickHouseHttpClient.send(ClickHouseHttpClient.java:101)
	at com.clickhouse.client.AbstractClient.sendAsync(AbstractClient.java:156)
	at com.clickhouse.client.AbstractClient.lambda$execute$0(AbstractClient.java:289)
	... 4 more
```

It looks like the `DESCRIBE TABLE` call is not back-quoting the table name, which is causing a SQL syntax error when the table name is not strictly alphanumeric.

### PR DESCRIPTION
**Pull request by mzitnik**
Handling special characters for table name  by doing escaping to table name
closes #38

### CODE REVIEW

**Comment by mzitnik** [comment]
Issue can be found  https://github.com/ClickHouse/clickhouse-kafka-connect/issues/38

File: src/main/java/com/clickhouse/kafka/connect/sink/db/ClickHouseWriter.java [hunk 1]
```diff
@@ -95,6 +95,9 @@ public void setBinary(boolean binary) {
         isBinary = binary;
     }
 
+    private String escapeTopicName(String topic) {
+        return String.format("`%s`", topic);
```
Comment (mshustov) [inline src/main/java/com/clickhouse/kafka/connect/sink/db/ClickHouseWriter.java:99]: Why does the table name escaping rules leak outside? The table name is be escaped on `L360` https://github.com/ClickHouse/clickhouse-kafka-connect/pull/39/files#diff-3180bd2c71e5c2af1a2aafe6ba0d52a50da1e97cefc6528911a35dda50c46ed0R360 isn't it?

File: src/test/java/com/clickhouse/kafka/connect/sink/ClickHouseSinkTaskSchemalessTest.java [hunk 2]
```diff
@@ -311,6 +311,32 @@ public void mapTypesTest() {
         assertEquals(sr.size(), countRows(chc, topic));
     }
 
+    @Test
+    // https://github.com/ClickHouse/clickhouse-kafka-connect/issues/38
+    public void specialCharTest() {
```
Comment (mshustov) [inline src/test/java/com/clickhouse/kafka/connect/sink/ClickHouseSinkTaskSchemalessTest.java:316]:
```suggestion
    public void specialCharTableNameTest() {
```

File: src/test/java/com/clickhouse/kafka/connect/sink/ClickHouseSinkTaskSchemalessTest.java [hunk 3]
```diff
@@ -88,7 +88,7 @@ private void createTable(ClickHouseHelperClient chc, String topic, String create
     }
 
     private int countRows(ClickHouseHelperClient chc, String topic) {
-        String queryCount = String.format("select count(*) from %s", topic);
+        String queryCount = String.format("select count(*) from `%s`", topic);
         try (ClickHouseClient client = ClickHouseClient.newInstance(ClickHouseProtocol.HTTP);
              ClickHouseResponse response = client.connect(chc.getServer()) // or client.connect(endpoints)
                      // you'll have to parse response manually if using a different format
```
Comment (mshustov) [inline src/test/java/com/clickhouse/kafka/connect/sink/ClickHouseSinkTaskSchemalessTest.java:94]: what about https://github.com/ClickHouse/clickhouse-kafka-connect/pull/39/files#diff-f5b98bbe450ebcd509fc383aca31a9810dcf20ba53c02b82241ee1f3bc30deb0R107 ?

**Review by mshustov — APPROVED** [review]

File: src/main/java/com/clickhouse/kafka/connect/sink/db/ClickHouseWriter.java (hunk 1 above)
Comment (mzitnik) [reply src/main/java/com/clickhouse/kafka/connect/sink/db/ClickHouseWriter.java:99]: We are escaping the topic name since when we get it from Map, the keys are already escaped. I planning to make a bigger refactor when adding also the database name to the map
